# Generated by Django 2.1.7 on 2019-10-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190925_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='用户唯一ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_from',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='用户来源'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(blank=True, default='favicon.ico', max_length=250, null=True, upload_to='img/'),
        ),
    ]
