# Generated by Django 2.1.7 on 2019-11-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191017_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(blank=True, default='favicon.ico', max_length=250, null=True, upload_to='img/', verbose_name='用户头像'),
        ),
    ]
