# Generated by Django 2.1.7 on 2019-10-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190922_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='head_pic_url',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='文章标题链接'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friend_url',
            field=models.CharField(default='http://', max_length=250, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(blank=True, default='favicon.ico', null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='zan',
            name='ip_address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
