# Generated by Django 2.1.7 on 2019-10-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_auto_20190811_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='extraction_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
