# Generated by Django 2.1.7 on 2019-11-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_auto_20191017_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='add_time',
            field=models.DateTimeField(verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='extraction_code',
            field=models.CharField(default='', max_length=20, verbose_name='提取密码'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.CharField(max_length=255, verbose_name='百度云链接地址'),
        ),
    ]
